#!/bin/bash
set -e

#i can't see why i did this - lets try moving it to the build itself
#pip install tensorrt --extra-index-url https://pypi.nvidia.com

# pip appears to leave behind 4GB of stuff.. lets remove it.
pip cache purge

#clean up some big files - maybe we don't need them
rm `find /srv/conda/envs -size +50M -name \*.a`

